version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: certificates
      MYSQL_USER: user123
      MYSQL_PASSWORD: senha123
    volumes:
      -./db-mysql/ddl.sql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "15672:15672" # Porta do painel de gerenciamento
      - "5672:5672"   # Porta de comunicação
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:alpine
    restart: always

  api:
    build:
      context: ./api # Direcionar para o diretório onde está o Dockerfile da API
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user123
      - DB_PASSWORD=senha123
      - DB_NAME=certificates
      - RABBITMQ_HOST=rabbitmq

  worker:
    build:
      context: ./worker # Direcionar para o diretório onde está o Dockerfile do Worker
    depends_on:
      - rabbitmq
      - redis
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user123
      - DB_PASSWORD=senha123
      - DB_NAME=certificates
      - RABBITMQ_HOST=rabbitmq

volumes:
  mysql_data:
