version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: certificates
      MYSQL_USER: user123
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - ./db-mysql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  api:
    build:
      context: ./api
    depends_on:
      - rabbitmq
      - mysql
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./pdfs:/app/pdfs  # Volume compartilhado para PDFs gerados
    environment:
      - REDIS_HOST=redis  # Definindo o host do Redis para a API

  worker:
    build:
      context: ./worker
    depends_on:
      - rabbitmq
      - mysql
    volumes:
      - ./pdfs:/app/pdfs  # Volume compartilhado para PDFs gerados

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"  # Porta padrão do Redis
