# Usar uma imagem base do Node.js
FROM node:14

# Criar diretório de trabalho
WORKDIR /app

# Copiar arquivos de dependências e instalar
COPY package*.json ./
RUN npm install

# Copiar o restante dos arquivos da aplicação
COPY . .

# Expor a porta da API
EXPOSE 3000

# Comando para iniciar a API
CMD ["node", "app.js"]
